let Mainproduct = [
  // array 안에 많은 상품들을 object 자료로 넣어둠
  {
    id: 0,
    color: ["mustard", "gray", "black", "olive"],
    title: "Over Heavy Wool Knit",
    content: "헤비한 중량감의 오버핏 울 니트",
    price: 67000,
    category: "top",
    size: ["S", "M", "L"],
    as: "교환/환불/as 규정",
  },
  {
    id: 1,
    title: "Round Toe Chelseaboots",
    content: "여유있는 2중 굽으로 제작된 레더 첼시부츠",
    price: 94000,
    category: "shoes",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 2,
    title: "Cos Cotton Jacket",
    content: "미니멀한 라인감의 하이퀄리티 코튼 자켓",
    price: 123000,
    category: "outer",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 3,
    title: "Hard Over Blazer Jacket ",
    content: "",
    price: 105000,
    category: "outer",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 4,
    title: "Triangle Leather Belt",
    content: "",
    price: 23000,
    category: "acc",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 5,
    title: "SemiWide Long Slacks",
    content: "",
    price: 53000,
    category: "bottom",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 6,
    title: "Over String Jacket",
    content: "",
    price: 117000,
    category: "outer",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 7,
    title: "Leather Mini Bag",
    content: "",
    price: 28000,
    category: "acc",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 8,
    title: "China Crop Jacket",
    content: "",
    price: 67000,
    category: "outer",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 9,
    title: "Hidden Button Jacket",
    content: "",
    price: 86000,
    category: "outer",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 10,
    title: "Minimal Leather Slipper",
    content: "",
    price: 49000,
    category: "shoes",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 11,
    title: "Crop Denim Jacket",
    content: "",
    price: 68000,
    category: "outer",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 12,
    title: "Slit Cotton Bag",
    content: "",
    price: 32000,
    category: "acc",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 13,
    title: "HighNeck Knit",
    content: "",
    price: 41000,
    category: "top",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 14,
    title: "Minimal Leather Belt",
    content: "",
    price: 21000,
    category: "acc",
    size: "",
    as: "교환/환불/as 규정",
  },
  {
    id: 15,
    title: "Argyel Wool KnitVest",
    content: "",
    price: 49000,
    category: "top",
    size: "",
    as: "교환/환불/as 규정",
  },
];

export default Mainproduct;
